### ISSUE TITLE
Ignite: org.apache.ignite.internal.binary.BinaryObjectImpl cannot be cast to java.lang.Comparable

### ISSUE THREAD

**Issue by gangliao** [DSLAM-UMD/FileScale#334]
```bash
Caused by: java.lang.ClassCastException: org.apache.ignite.internal.binary.BinaryObjectImpl cannot be cast to java.lang.Comparable
	at java.util.TreeMap.compare(TreeMap.java:1294)
	at java.util.TreeMap.put(TreeMap.java:538)
	at org.apache.hadoop.hdfs.db.ignite.RenameSubtreeINodes.apply(RenameSubtreeINodes.java:75)
	at org.apache.hadoop.hdfs.db.ignite.RenameSubtreeINodes.apply(RenameSubtreeINodes.java:24)
	at org.apache.ignite.internal.processors.closure.GridClosureProcessor$C1.execute(GridClosureProcessor.java:1756)
	at org.apache.ignite.internal.processors.job.GridJobWorker$2.call(GridJobWorker.java:598)
	at org.apache.ignite.internal.util.IgniteUtils.wrapThreadLoader(IgniteUtils.java:7085)
	at org.apache.ignite.internal.processors.job.GridJobWorker.execute0(GridJobWorker.java:592)
	... 12 more

	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1516)
	at org.apache.hadoop.ipc.Client.call(Client.java:1462)
	at org.apache.hadoop.ipc.Client.call(Client.java:1372)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
	at com.sun.proxy.$Proxy9.rename(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.rename(ClientNamenodeProtocolTranslatorPB.java:592)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy10.rename(Unknown Source)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark$RenameDirStats.executeOp(NNThroughputBenchmark.java:1176)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark$StatsDaemon.benchmarkOne(NNThroughputBenchmark.java:461)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark$StatsDaemon.run(NNThroughputBenchmark.java:444)
```

**Comment by gangliao** [comment]
```bash
org.apache.hadoop.ipc.RemoteException(org.apache.ignite.IgniteException): class org.apache.ignite.IgniteException: Remote job threw user exception (override or implement ComputeTask.result(..) method if you would like to have automatic failover for this exception): Only pessimistic transactions are supported when MVCC is enabled.
```
